
import { GoogleAnalytics } from '@next/third-parties/google'
import type { Metadata } from 'next'
import { cookies } from 'next/headers'
import Script from 'next/script'
import NextTopLoader from 'nextjs-toploader'
import { ReactNode } from 'react'

import { LanguageProvider } from '@/components/Provider'
import ReactQueryProvider from '@/components/Provider/ReactQuery'
import { Footer } from '@/components/shared/Footer'
import { Header } from '@/components/shared/Header'
import { NavigationEvents } from '@/components/shared/NavigationEvents'
import { keppler, neue } from '@/lib/fonts'
import { getTranslationData } from '@/resources/i18n/i18n'
import { I18nProvider } from '@/resources/i18n/i18n.context'

import './globals.css'

export const metadata: Metadata = {
  title: 'LFA - Interior Design',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const cookieStore = cookies()
  const lang = cookieStore.get('LOCALE_COOKIE_KEY')?.value || 'en-US'

  const translationData = await getTranslationData(lang)

  return (
    <ReactQueryProvider>
      <html lang='en'>
        <head>
          <meta name="google-site-verification" content="h0EHt24PUKTS9IO6LxQooYKlUbNjLqDKUfRdKWDs_EI" />
          <Script
            strategy="afterInteractive"
            src={`https://www.googletagmanager.com/gtag/js?id=G-ZG702WCMGJ`}
          />
          <GoogleAnalytics gaId="G-ZG702WCMGJ" />
        </head>
        <body className={`${neue.variable} ${keppler.variable}`}>
          <NextTopLoader color='#252525' />
          <LanguageProvider>
            <I18nProvider data={JSON.parse(JSON.stringify(translationData))}>
              <Header />
              {children}
              <Footer />
            </I18nProvider>
          </LanguageProvider>
          <NavigationEvents />
        </body>
      </html>
    </ReactQueryProvider>
  )
}
