export enum EQueryKey {
  'PROJECT' = 'project',
  'PROJECT_MINIMAL' = 'projectMinimal',
  'CLIENT' = 'client',
  'AWARD' = 'award',
  'ARTICLE' = 'article',
  'RECOGNITION' = 'recognition',
  'SERVICE' = 'service',
  'TESTIMONIAL' = 'testimonial',
  'INDUSTRY' = 'industry',
  'REGION' = 'region',
  'TEAM' = 'team',
  'CONTACT' = 'contact',
  'FAQ' = 'faq',
  'PRIVACY_POLICY' = 'privacyPolicy',
  'TNC' = 'tnc',
}
