import type { Metadata } from 'next'
import { ReactNode } from 'react'
import NextTopLoader from 'nextjs-toploader'

import { LanguageProvider } from '@/components/Provider'
import ReactQueryProvider from '@/components/Provider/ReactQuery'
import { Footer } from '@/components/shared/Footer'
import { Header } from '@/components/shared/Header'
import { keppler, neue } from '@/lib/fonts'
import { getTranslationData } from '@/resources/i18n/i18n'
import { I18nProvider } from '@/resources/i18n/i18n.context'

import './globals.css'
import { NavigationEvents } from '@/components/shared/NavigationEvents'

export const metadata: Metadata = {
  title: 'LFA - Interior Design',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
  params: {
    lang: string
  }
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const translationData = await getTranslationData(params.lang)

  return (
    <ReactQueryProvider>
      <html lang='en'>
        <body className={`${neue.variable} ${keppler.variable}`}>
          <NextTopLoader color='#252525' />
          <LanguageProvider lang={params.lang}>
            <I18nProvider data={JSON.parse(JSON.stringify(translationData))}>
              <Header />
              {children}
              <Footer />
            </I18nProvider>
          </LanguageProvider>
          <NavigationEvents />
        </body>
      </html>
    </ReactQueryProvider>
  )
}
